//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerretruckASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_product
    {
        public int id { get; set; }
        public Nullable<int> codigo_p { get; set; }
        public Nullable<int> id_c { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual categoria categoria { get; set; }
    }
}
