//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerretruckASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_venta
    {
        public int id_detalle { get; set; }
        public Nullable<int> catidad { get; set; }
        public Nullable<int> precio_total { get; set; }
        public Nullable<int> estado_venta { get; set; }
        public Nullable<int> descuento { get; set; }
        public Nullable<int> codigo_p { get; set; }
        public Nullable<int> no_folio { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual venta venta { get; set; }
    }
}
